### ISSUE TITLE
Data Visualization Pipeline

### ISSUE THREAD

**Issue by Monde0** [Monde0/ALVR-thai-trial#1]
As a personal open-source project owner, even if our open source has statistical data visualized in the user interfaces of our application. I think if there is any possible way to visualize those data outside.

**Comment by fame-git** [comment]
Hi, I am happy to work on this issues, this is the roughly sketch for this issues. I planned to came up with 2 approaches. 1 is a local infrastructure for data visualization (Docker based) and native cloud infrastructure.
